#!/usr/bin/env php
<?php
/*
 * EN : Console Application setup and bootstrap
 * Allows interacting with the app in the command line interface
 * 
 */
// autoloader
require_once __DIR__ . '/vendor/autoload.php';
// application
require __DIR__ . '/src/app.php';
// console object
$console = require __DIR__ . '/src/console.php';
// run
$console->run();
