<?php
namespace Ribbit\DataAccessLayer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:52.
 */
class DoctrineRoleProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DoctrineRoleProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineRoleProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineRoleProvider::getByTitle
     * @todo   Implement testGetByTitle().
     */
    public function testGetByTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
