<?php
namespace Ribbit\DataAccessLayer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:52.
 */
class DoctrineUserProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DoctrineUserProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineUserProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::getByUsername
     * @todo   Implement testGetByUsername().
     */
    public function testGetByUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::getByEmail
     * @todo   Implement testGetByEmail().
     */
    public function testGetByEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::getById
     * @todo   Implement testGetById().
     */
    public function testGetById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::getFollowerCount
     * @todo   Implement testGetFollowerCount().
     */
    public function testGetFollowerCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineUserProvider::getFollowers
     * @todo   Implement testGetFollowers().
     */
    public function testGetFollowers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
