<?php
namespace Ribbit\DataAccessLayer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:51.
 */
class DoctrineRibbitProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DoctrineRibbitProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineRibbitProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineRibbitProvider::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineRibbitProvider::findByUser
     * @todo   Implement testFindByUser().
     */
    public function testFindByUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineRibbitProvider::findFolloweeRibbits
     * @todo   Implement testFindFolloweeRibbits().
     */
    public function testFindFolloweeRibbits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\DataAccessLayer\DoctrineRibbitProvider::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
