<?php
namespace Ribbit\Services\SQLLogger;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:59.
 */
class MonologSQLLoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MonologSQLLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MonologSQLLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\Services\SQLLogger\MonologSQLLogger::startQuery
     * @todo   Implement testStartQuery().
     */
    public function testStartQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\Services\SQLLogger\MonologSQLLogger::stopQuery
     * @todo   Implement testStopQuery().
     */
    public function testStopQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
