<?php
namespace Ribbit\BusinessLogicLayer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:54.
 */
class RoleManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RoleManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RoleManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\RoleManager::getByTitle
     * @todo   Implement testGetByTitle().
     */
    public function testGetByTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
