<?php
namespace Ribbit\BusinessLogicLayer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:55.
 */
class UserManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::loadUserByUsername
     * @todo   Implement testLoadUserByUsername().
     */
    public function testLoadUserByUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::getByEmail
     * @todo   Implement testGetByEmail().
     */
    public function testGetByEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::getById
     * @todo   Implement testGetById().
     */
    public function testGetById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::refreshUser
     * @todo   Implement testRefreshUser().
     */
    public function testRefreshUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::follow
     * @todo   Implement testFollow().
     */
    public function testFollow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::unfollow
     * @todo   Implement testUnfollow().
     */
    public function testUnfollow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::supportsClass
     * @todo   Implement testSupportsClass().
     */
    public function testSupportsClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::encodePassword
     * @todo   Implement testEncodePassword().
     */
    public function testEncodePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::setNewPassword
     * @todo   Implement testSetNewPassword().
     */
    public function testSetNewPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::setNewPasswordByUsername
     * @todo   Implement testSetNewPasswordByUsername().
     */
    public function testSetNewPasswordByUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\BusinessLogicLayer\UserManager::setUserSalt
     * @todo   Implement testSetUserSalt().
     */
    public function testSetUserSalt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
