<?php
namespace Ribbit\Services\Provider;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 04:45:58.
 */
class DoctrineORMServiceProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DoctrineORMServiceProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineORMServiceProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ribbit\Services\Provider\DoctrineORMServiceProvider::boot
     * @todo   Implement testBoot().
     */
    public function testBoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ribbit\Services\Provider\DoctrineORMServiceProvider::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
